### ISSUE TITLE
Won't load in Brave Browser Manifest file is missing or unreadable.

### ISSUE THREAD

**Issue by PeEcEeChIP** [Daw588/rwp#2]
![image](https://user-images.githubusercontent.com/20268209/187682923-d1da75e4-0813-4627-bcef-3fc00e38b174.png)

**Comment by Daw588** [comment]
Did you load the browser extension from the extension folder?

**Comment by Daw588** [comment]
You are not supposed to load the entire project folder in, only the folder called extension.

**Comment by PeEcEeChIP** [comment]
Oh, im stupid.
